services:
  problem5-service:
    image: 'postgres:16'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=problem5
      - POSTGRES_PASSWORD=problem5
      - POSTGRES_DB=problem5
    networks:
      - problem5-database-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
